var icon;
var logout;
var modalIsOpen = false;
var messagesLength = 0;
var ctModalOpen = 0;
var senderId = 0;
var receiverId = 0;
var chatButtonEvent;
var fileName = "";
var fileBytes = "";
let objectURL;
const chatModal = document.getElementById('chatModal');